CREATE DATABASE FATEC_SOLICITACOES;

USE FATEC_SOLICITACOES;
SELECT @@VERSION_COMMENT;

CREATE TABLE T_TICKETS (
  id_ticket INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  tipo_vinculo VARCHAR(50) NOT NULL,
  ra VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  assunto VARCHAR(100) NOT NULL,
  data_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resposta VARCHAR(100),
  status VARCHAR(50) DEFAULT 'Pendente',
  data_resposta TIMESTAMP NULL DEFAULT NULL,
  nome_usuario_adm_respondeu VARCHAR(100),
  id_usuario INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE T_USUARIOS (
  id_usuario INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tipo_perfil VARCHAR(100) NOT NULL -- CADASTRA TANTO ADM QUANTO USUARIO ALUNO
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE T_DOCUMENTO (
  id_doc INT PRIMARY KEY AUTO_INCREMENT,
  nome_doc VARCHAR(100) NOT NULL,
  status_doc VARCHAR(100) NOT NULL -- TABULAR COMO DOCUMENTO ATIVO OU INATIVO
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE T_SOLICITACOES (
  id_solicitacao INT PRIMARY KEY AUTO_INCREMENT,
  ra VARCHAR(20) NOT NULL,
  telefone CHAR(11) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  rg VARCHAR(14) NOT NULL,
  id_doc INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- UNIQUE
ALTER TABLE T_USUARIOS
ADD CONSTRAINT UN_EMAIL_USUARIOS
UNIQUE (email);

ALTER TABLE T_DOCUMENTO
ADD CONSTRAINT UN_NOME_DOCUMENTO
UNIQUE (nome_doc);

-- CHAVE ESTRANGEIRA
ALTER TABLE T_SOLICITACOES
ADD CONSTRAINT FK_VINCULO_SOLICI_DOC
FOREIGN KEY (id_doc)
REFERENCES T_DOCUMENTO(id_doc)
ON DELETE CASCADE
ON UPDATE CASCADE;
